const TCS_API_BASE = 'https://marketplace-c3wq.onrender.com';
function apiUrl(path){return TCS_API_BASE+path}


function money(v,type){if(type==='Price on Request')return type;return (type&&type!=='Fixed'?type+' ':'')+'R '+Number(v||0).toLocaleString('en-ZA')}
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function json(url,opt){const r=await fetch(apiUrl(url),opt);const x=await r.json().catch(()=>({error:'Invalid response'}));if(!r.ok)throw Error(x.error||'Request failed');return x}
function waNumber(v){let n=String(v||'').replace(/\D/g,'');if(n.startsWith('0')&&n.length===10)n='27'+n.slice(1);return n.startsWith('27')&&n.length===11?n:''}
function mediaUrl(v){const u=String(v||'');return u.startsWith('/')?apiUrl(u):u}
function iconFor(c){return ({'Towing & Recovery':'🚚','TLBs & Earthmoving':'🚜','Tractors':'🌾','Trucks & Bakkies':'🚛','Industrial Equipment':'⚙️','Parts & Accessories':'🔩'})[c]||'📦'}
function listingCard(x){
 const img=x.coverImage?`<img class="listing-image" src="${esc(mediaUrl(x.coverImage))}" alt="${esc(x.title)}">`:`<div class="mock-img"><span>${iconFor(x.category)}</span><b>${esc(x.category)}</b></div>`;
 const wa=waNumber(x.whatsapp);
 const details=`<a class="btn secondary" href="listing.html?slug=${encodeURIComponent(x.slug)}">View Details</a>`;
 return `<article class="card listing-card">${img}<span class="status approved">${esc(x.listingKind||'listing')}</span><h3>${esc(x.title)}</h3><div class="price">${money(x.price,x.priceType)}</div><p>${esc(x.description).slice(0,190)}</p><p class="muted">${esc(x.town)}, ${esc(x.province)} · ${esc(x.condition)}</p><div class="listing-actions">${details}<a class="btn secondary" href="contact-seller.html?listing=${encodeURIComponent(x.slug||x.id)}">Email Seller</a>${wa?`<a class="btn whatsapp" target="_blank" href="https://wa.me/${wa}?text=${encodeURIComponent('Hi, I am interested in '+x.title)}">WhatsApp</a>`:''}<button class="btn warn" onclick="reportListing('${esc(x.id)}')">Report Advert</button></div></article>`
}
async function loadListings(){const el=document.getElementById('listingGrid');if(!el)return;const q=document.getElementById('mq')?.value||'',category=document.getElementById('mcat')?.value||'',province=document.getElementById('mprovince')?.value||'';try{let rows=await json(`/api/listings/public?q=${encodeURIComponent(q)}&category=${encodeURIComponent(category)}&province=${encodeURIComponent(province)}`);el.innerHTML=rows.length?rows.map(listingCard).join(''):'<div class="box"><b>No approved listings yet.</b><p>Place the first real advert.</p></div>'}catch(e){el.innerHTML='<div class="notice"><b>Could not load the shared marketplace.</b><p>Refresh after the Render service wakes up.</p></div>'}}
async function loadDetail(){const el=document.getElementById('listingDetail');if(!el)return;const slug=new URLSearchParams(location.search).get('slug');try{const x=await json('/api/listings/public/'+encodeURIComponent(slug));const photos=(x.images||[]).map((i,n)=>`<img src="${esc(mediaUrl(i))}" alt="Listing photo ${n+1}">`).join('');const wa=waNumber(x.whatsapp);el.innerHTML=`<div class="listing-gallery">${photos||'<div class="mock-img">No photos uploaded</div>'}</div><div class="box"><span class="status approved">Approved listing</span><h1>${esc(x.title)}</h1><div class="price">${money(x.price,x.priceType)}</div><p>${esc(x.description)}</p><p><b>Category:</b> ${esc(x.category)}</p><p><b>Location:</b> ${esc(x.town)}, ${esc(x.province)}</p><p><b>Condition:</b> ${esc(x.condition)}</p>${x.year?`<p><b>Year:</b> ${esc(x.year)}</p>`:''}${x.usage?`<p><b>Usage:</b> ${esc(x.usage)}</p>`:''}${wa?`<a class="btn whatsapp" target="_blank" href="https://wa.me/${wa}?text=${encodeURIComponent('Hi, I am interested in '+x.title)}">WhatsApp Seller</a>`:''}${x.phone?`<a class="btn secondary" href="tel:${esc(x.phone)}">Call Seller</a>`:''}</div>`}catch(e){el.innerHTML='<div class="notice">Listing not found.</div>'}}
function preview(){const el=document.getElementById('imagePreview'),inp=document.getElementById('images');if(!el||!inp)return;el.innerHTML='';[...inp.files].slice(0,12).forEach(f=>{const i=document.createElement('img');i.src=URL.createObjectURL(f);el.appendChild(i)})}
async function submitListing(e){e.preventDefault();const out=document.getElementById('result');out.textContent='Uploading to the shared marketplace...';try{const r=await fetch(apiUrl('/api/listings/create'),{method:'POST',body:new FormData(e.target)});const type=r.headers.get('content-type')||'';const raw=await r.text();let x={};if(type.includes('application/json')){try{x=JSON.parse(raw)}catch(parseError){throw Error('The marketplace API returned invalid JSON')}}else{throw Error('The Render API route is not active yet. Deploy this complete build to Render and try again')}if(!r.ok||!x.ok)throw Error(x.error||'Upload failed');out.innerHTML='<span class="status pending">Advert submitted successfully. Reference: '+esc(x.listing.id)+'. Waiting for Admin approval.</span>';e.target.reset();preview()}catch(err){out.innerHTML='<span class="status rejected">Could not submit to the shared marketplace: '+esc(err.message)+'</span>'}}
async function loadAdmin(){const el=document.getElementById('adminListings');if(!el)return;try{const rows=await json('/api/listings/admin/pending',{headers:{'x-demo-user':'u_admin_1'}});el.innerHTML=rows.length?rows.map(x=>`<div class="card">${x.coverImage?`<img class="listing-image" src="${esc(mediaUrl(x.coverImage))}">`:''}<h3>${esc(x.title)}</h3><p>${esc(x.description)}</p><div class="price">${money(x.price,x.priceType)}</div><button onclick="review('${x.id}','approve')">Approve</button><button class="btn danger" onclick="review('${x.id}','reject')">Reject</button></div>`).join(''):'<div class="box">No pending listings.</div>'}catch(e){el.innerHTML='<div class="notice">Could not load the shared Admin review queue. Refresh after the Render service wakes up.</div>'}}
async function review(id,action){let body='{}';if(action==='reject')body=JSON.stringify({reason:prompt('Reject reason:')||'Rejected by admin'});await json('/api/listings/admin/'+id+'/'+action,{method:'POST',headers:{'Content-Type':'application/json','x-demo-user':'u_admin_1'},body});loadAdmin()}
addEventListener('DOMContentLoaded',()=>{loadListings();loadDetail();loadAdmin();document.getElementById('images')?.addEventListener('change',preview);document.getElementById('listingForm')?.addEventListener('submit',submitListing)});

async function reportListing(id){const reason=prompt('Why are you reporting this advert?');if(!reason)return;try{const r=await fetch(apiUrl('/api/marketplace-live/public/report/'+encodeURIComponent(id)),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reason})});const x=await r.json();if(!r.ok)throw Error(x.error||'Report failed');alert('Report received. Reference: '+x.reference)}catch(e){alert(e.message)}}
